### ISSUE TITLE
Strange error from siad

### ISSUE THREAD

**Issue by Firescar96** [NebulousLabs/NebulousLabs.github.io#3]
siad gives a strange error, not immediately after starting, but after starting mining in siac.

A lock was held for too long, id '12030'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:120'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:126'
A lock was held until deadlock, subsequent call to unlock failed. id '12030'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:125'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:220'
A lock was held until deadlock, subsequent call to unlock failed. id '27'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/dump.go:40'
A lock was held until deadlock, subsequent call to unlock failed. id '12026'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:125'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:113'
A lock was held for too long, id '28'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/dump.go:14'
A lock was held for too long, id '12372'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:120'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:109'
A lock was held for too long, id '12375'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:120'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:126'
A lock was held until deadlock, subsequent call to unlock failed. id '12375'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:125'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:220'
A lock was held until deadlock, subsequent call to unlock failed. id '28'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/dump.go:40'
A lock was held until deadlock, subsequent call to unlock failed. id '12372'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:125'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:113'
A lock was held for too long, id '48428'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:120'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:109'
A lock was held for too long, id '2909'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/dump.go:14'
A lock was held until deadlock, subsequent call to unlock failed. id '2909'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/transactionpool/dump.go:40'
A lock was held until deadlock, subsequent call to unlock failed. id '48428'. Call stack:
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/consensus/state.go:125'
        File: '/home/david/dev/gopath/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:113'

over and over of various lines of code. Hardcoded file path?

**Comment by lukechampine** [comment]
This is a benign error caused by our mutex handling, which isn't yet 100% watertight. These errors can be safely ignored, and shouldn't be present in future releases. See https://github.com/NebulousLabs/Sia-UI/issues/90 (btw, this isn't really the right repo for this issue).

The file path is indeed hardcoded; it's generated by the Go `runtime` package during compilation. So if you run a binary compiled on someone else's machine, you'll see their path.

**Comment by Firescar96** [comment]
Yeah, this is the way wrong repo, soz. Thanks
